In [9]:
import numpy as np
X = np.array(([2,9], [1,5], [3,6]), dtype=float)
Y = np.array(([92], [86], [89]), dtype=float)
print(X)
print(Y)

X = X/np.amax(X, axis=0)
actual_op = Y/100

print(X)
print(Y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[92.]
 [86.]
 [89.]]


In [10]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative_sigmoid(x):
    return x*(1-x)


In [11]:
np.random.seed(1)
epoch = 1000
lr = 0.15
ip_neuron = 2; hidden_neuron = 3; op_neuron = 1

wh = np.random.uniform(low = -0.05, high = 0.05, size=(ip_neuron, hidden_neuron)) #weight
bh = np.random.uniform(low = -0.05, high = 0.05, size=(1, hidden_neuron)) #bias

wo = np.random.uniform(low = -0.05, high = 0.05, size=(hidden_neuron, op_neuron))
bo = np.random.uniform(low = -0.05, high = 0.05, size=(1, op_neuron))

print(f'wh{wh}\nbh{bh}\nwo{wo}\nbo{bo}')

wh[[-0.0082978   0.02203245 -0.04998856]
 [-0.01976674 -0.03532441 -0.04076614]]
bh[[-0.03137398 -0.01544393 -0.01032325]]
wo[[ 0.00388167]
 [-0.00808055]
 [ 0.01852195]]
bo[[-0.02955478]]


In [12]:
#Train using back propagation

for i in range(epoch):
    net_h = np.dot(X, wh)+bh
    sigma_h = sigmoid(net_h)
    
    net_o = np.dot(sigma_h, wo)+bo
    output = sigmoid(net_o)
    
    eo = actual_op - output
    outgrad = derivative_sigmoid(output)
    d_output = eo*outgrad #err = oj(1-oj)(tj-oj)
    
    eh = d_output.dot(wo.T)
    hiddengrad = derivative_sigmoid(sigma_h)
    
    d_hidden = eh*hiddengrad
    
    wo += sigma_h.T.dot(d_output)*lr
    wh += X.T.dot(d_hidden)*lr
    
    sum_error = 0
    for j in range(len(actual_op)):
        print(output[j], actual_op[j])
        sum_error += (output[j] - actual_op[j])**2
        
    sum_error = sum_error/2
    print(f'Epoch {i} error {sum_error}')
    

[0.49430875] [0.92]
[0.49434754] [0.86]
[0.49429647] [0.89]
Epoch 0 error [0.23574802]
[0.50220152] [0.92]
[0.50231365] [0.86]
[0.50221652] [0.89]
Epoch 1 error [0.22643556]
[0.50993918] [0.92]
[0.51012171] [0.86]
[0.50998083] [0.89]
Epoch 2 error [0.21748963]
[0.51752156] [0.92]
[0.51777004] [0.86]
[0.51758915] [0.89]
Epoch 3 error [0.20890004]
[0.52494889] [0.92]
[0.52525755] [0.86]
[0.52504159] [0.89]
Epoch 4 error [0.20065627]
[0.53222169] [0.92]
[0.53258365] [0.86]
[0.53233863] [0.89]
Epoch 5 error [0.19274757]
[0.53934082] [0.92]
[0.53974826] [0.86]
[0.53948105] [0.89]
Epoch 6 error [0.18516306]
[0.54630735] [0.92]
[0.54675173] [0.86]
[0.54646989] [0.89]
Epoch 7 error [0.1778918]
[0.55312263] [0.92]
[0.55359481] [0.86]
[0.55330645] [0.89]
Epoch 8 error [0.17092285]
[0.55978819] [0.92]
[0.5602786] [0.86]
[0.55999222] [0.89]
Epoch 9 error [0.1642453]
[0.56630572] [0.92]
[0.56680452] [0.86]
[0.5665289] [0.89]
Epoch 10 error [0.15784839]
[0.5726771] [0.92]
[0.57317426] [0.86]
[0.5729

[0.87346203] [0.92]
[0.85843502] [0.86]
[0.87320434] [0.89]
Epoch 256 error [0.00122516]
[0.87361927] [0.92]
[0.85858021] [0.86]
[0.87336028] [0.89]
Epoch 257 error [0.00121503]
[0.87377517] [0.92]
[0.85872416] [0.86]
[0.8735149] [0.89]
Epoch 258 error [0.00120506]
[0.87392975] [0.92]
[0.85886691] [0.86]
[0.8736682] [0.89]
Epoch 259 error [0.00119524]
[0.87408303] [0.92]
[0.85900844] [0.86]
[0.87382021] [0.89]
Epoch 260 error [0.00118557]
[0.87423501] [0.92]
[0.85914879] [0.86]
[0.87397092] [0.89]
Epoch 261 error [0.00117605]
[0.87438571] [0.92]
[0.85928796] [0.86]
[0.87412037] [0.89]
Epoch 262 error [0.00116667]
[0.87453515] [0.92]
[0.85942596] [0.86]
[0.87426856] [0.89]
Epoch 263 error [0.00115743]
[0.87468334] [0.92]
[0.85956282] [0.86]
[0.8744155] [0.89]
Epoch 264 error [0.00114833]
[0.8748303] [0.92]
[0.85969853] [0.86]
[0.87456122] [0.89]
Epoch 265 error [0.00113937]
[0.87497603] [0.92]
[0.85983311] [0.86]
[0.87470571] [0.89]
Epoch 266 error [0.00113055]
[0.87512055] [0.92]
[0.85

[0.88804325] [0.92]
[0.87188028] [0.86]
[0.88763106] [0.89]
Epoch 418 error [0.00058399]
[0.88809134] [0.92]
[0.8719243] [0.86]
[0.88767841] [0.89]
Epoch 419 error [0.00058287]
[0.88813912] [0.92]
[0.87196804] [0.86]
[0.88772544] [0.89]
Epoch 420 error [0.00058176]
[0.8881866] [0.92]
[0.87201149] [0.86]
[0.88777218] [0.89]
Epoch 421 error [0.00058067]
[0.88823376] [0.92]
[0.87205465] [0.86]
[0.8878186] [0.89]
Epoch 422 error [0.00057958]
[0.88828063] [0.92]
[0.87209753] [0.86]
[0.88786473] [0.89]
Epoch 423 error [0.00057851]
[0.88832719] [0.92]
[0.87214013] [0.86]
[0.88791055] [0.89]
Epoch 424 error [0.00057746]
[0.88837345] [0.92]
[0.87218245] [0.86]
[0.88795608] [0.89]
Epoch 425 error [0.00057641]
[0.88841942] [0.92]
[0.87222449] [0.86]
[0.88800132] [0.89]
Epoch 426 error [0.00057538]
[0.8884651] [0.92]
[0.87226626] [0.86]
[0.88804626] [0.89]
Epoch 427 error [0.00057436]
[0.88851048] [0.92]
[0.87230775] [0.86]
[0.88809091] [0.89]
Epoch 428 error [0.00057336]
[0.88855557] [0.92]
[0.87

[0.89435631] [0.92]
[0.8775175] [0.86]
[0.89377995] [0.89]
Epoch 679 error [0.00048937]
[0.89436675] [0.92]
[0.87752615] [0.86]
[0.89378983] [0.89]
Epoch 680 error [0.0004893]
[0.89437714] [0.92]
[0.87753476] [0.86]
[0.89379965] [0.89]
Epoch 681 error [0.00048922]
[0.89438747] [0.92]
[0.8775433] [0.86]
[0.89380942] [0.89]
Epoch 682 error [0.00048914]
[0.89439774] [0.92]
[0.8775518] [0.86]
[0.89381913] [0.89]
Epoch 683 error [0.00048906]
[0.89440796] [0.92]
[0.87756024] [0.86]
[0.89382878] [0.89]
Epoch 684 error [0.00048899]
[0.89441812] [0.92]
[0.87756863] [0.86]
[0.89383838] [0.89]
Epoch 685 error [0.00048891]
[0.89442823] [0.92]
[0.87757697] [0.86]
[0.89384793] [0.89]
Epoch 686 error [0.00048884]
[0.89443828] [0.92]
[0.87758526] [0.86]
[0.89385742] [0.89]
Epoch 687 error [0.00048876]
[0.89444828] [0.92]
[0.8775935] [0.86]
[0.89386686] [0.89]
Epoch 688 error [0.00048869]
[0.89445823] [0.92]
[0.87760169] [0.86]
[0.89387624] [0.89]
Epoch 689 error [0.00048861]
[0.89446812] [0.92]
[0.877

[0.89544587] [0.92]
[0.87836411] [0.86]
[0.89478671] [0.89]
Epoch 830 error [0.00048153]
[0.89545063] [0.92]
[0.8783674] [0.86]
[0.89479094] [0.89]
Epoch 831 error [0.00048149]
[0.89545538] [0.92]
[0.87837067] [0.86]
[0.89479515] [0.89]
Epoch 832 error [0.00048146]
[0.8954601] [0.92]
[0.87837392] [0.86]
[0.89479933] [0.89]
Epoch 833 error [0.00048142]
[0.89546479] [0.92]
[0.87837714] [0.86]
[0.89480349] [0.89]
Epoch 834 error [0.00048138]
[0.89546946] [0.92]
[0.87838035] [0.86]
[0.89480763] [0.89]
Epoch 835 error [0.00048135]
[0.89547411] [0.92]
[0.87838353] [0.86]
[0.89481174] [0.89]
Epoch 836 error [0.00048131]
[0.89547874] [0.92]
[0.87838669] [0.86]
[0.89481583] [0.89]
Epoch 837 error [0.00048128]
[0.89548334] [0.92]
[0.87838983] [0.86]
[0.8948199] [0.89]
Epoch 838 error [0.00048124]
[0.89548792] [0.92]
[0.87839294] [0.86]
[0.89482395] [0.89]
Epoch 839 error [0.00048121]
[0.89549248] [0.92]
[0.87839604] [0.86]
[0.89482797] [0.89]
Epoch 840 error [0.00048117]
[0.89549702] [0.92]
[0.8

In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'